apiVersion: v1
kind: Service
metadata:
  name: personal-diary-api-service
  namespace: personal-diary
  labels:
    app.kubernetes.io/name: personal-diary-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: personal-diary
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: personal-diary-api
    app.kubernetes.io/component: backend